# Generated by Django 2.2.4 on 2020-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20200305_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
