# Generated by Django 3.2.6 on 2021-08-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0007_auto_20210804_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaboProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diabo_profile', to='user_profile.userprofile')),
            ],
        ),
    ]
