# Generated by Django 3.2.6 on 2021-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaboprofile',
            name='diabetes_type',
            field=models.CharField(blank=True, choices=[('0', 'Diabetes Type 1'), ('1', 'Diabetes Type 2')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='diabo.job')),
            ],
        ),
        migrations.AddField(
            model_name='diaboprofile',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diabo.job'),
        ),
    ]
