# Generated by Django 3.2.6 on 2021-08-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtherapy',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withmealtherapy',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
