# Generated by Django 3.2.6 on 2021-08-20 16:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('diabetes_therapy', '0002_auto_20210818_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TherapyType',
            new_name='TherapyCategory',
        ),
    ]
