# Generated by Django 3.2.6 on 2021-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkingsnapshot',
            name='location_data',
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsnapshot',
            name='speed_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LocationData',
        ),
    ]
