# Generated by Django 3.2.6 on 2021-09-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_remove_userprofile_diabetes_type'),
        ('walking_tracker', '0002_auto_20210928_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkingtrackersession',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
