# Generated by Django 2.2.4 on 2021-07-10 08:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import xapp.api_v1.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('nick_name', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^(\\+98|0)?9\\d{9}$')])),
                ('verification_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Verified')], default='0', max_length=1)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfilePhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=xapp.api_v1.helpers.generate_code, max_length=13)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('query_times', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('burnt', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='xapp.UserProfile')),
            ],
        ),
    ]
