# Generated by Django 3.2.3 on 2021-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210514_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
