# Generated by Django 3.2.3 on 2021-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
