# Generated by Django 3.2.6 on 2021-08-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210804_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='national_code',
        ),
    ]
