# Generated by Django 3.2.6 on 2021-08-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user_profile', '0006_remove_userprofile_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.region'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Neighbor',
        ),
    ]
