# Generated by Django 3.2.6 on 2021-08-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210804_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diabetes_type',
        ),
    ]
